export type Question = {id:string;language:'fr-FR';nativeLanguage:'en';type:'multiple_choice'|'translation'|'sentence_builder'|'listening';prompt:string;correctAnswer:string;incorrectAnswers:string[];explanation:{en:string};pronunciationGuide:string;respelling:string;difficulty:'easy'|'medium';topic:'vocabulary'|'grammar'|'conversation'|'listening';level:number;proficiency:'A1';xpReward:number;audio:string;image:string;cultureNote:string;tags:string[];example:string;hint:string};
function q(id:string,level:number,prompt:string,answer:string,wrong:string[],explanation:string,ipa:string,respelling:string,example:string,hint:string,type:Question['type']='multiple_choice',audio=answer):Question{return{id,language:'fr-FR',nativeLanguage:'en',type,prompt,correctAnswer:answer,incorrectAnswers:wrong,explanation:{en:explanation},pronunciationGuide:ipa,respelling,difficulty:type==='sentence_builder'?'medium':'easy',topic:type==='listening'?'listening':type==='sentence_builder'?'grammar':'vocabulary',level,proficiency:'A1',xpReward:type==='sentence_builder'?20:10,audio,image:'',cultureNote:'',tags:['foundations',`unit-${level}`],example,hint};}
export const units=[{id:1,title:'First words',subtitle:'A hello can open a whole new world.',words:'Greetings · politeness · goodbyes',icon:'hello'},{id:2,title:'About you',subtitle:'Make your very first introduction.',words:'Names · introductions · être',icon:'person'},{id:3,title:'At the café',subtitle:'Order a little something in French.',words:'Drinks · requests · politeness',icon:'cafe'},{id:4,title:'Out & about',subtitle:'Find your way, one phrase at a time.',words:'Directions · places · questions',icon:'compass'}];
export const questions:Question[]=[
q('fr-001',1,'How do you say “hello” during the day?','Bonjour',['Merci','Au revoir','Bonne nuit'],'Bonjour is a daytime greeting. Bon means “good” and jour means “day”.','/bɔ̃.ʒuʁ/','bohn-ZHOOR','Bonjour, madame. — Hello, ma’am.','Think of a good day.'),
q('fr-002',1,'Someone helps you. How do you say “thank you”?','Merci',['Bonjour','Salut','Bonsoir'],'Merci means “thank you”. Add beaucoup to say “thank you very much”.','/mɛʁ.si/','mehr-SEE','Merci beaucoup. — Thank you very much.','It starts with “mer”.'),
q('fr-003',1,'Type the French word for “yes”.','Oui',[],'Oui means “yes”. The letters ou together usually make an “oo” sound; here the word sounds like “wee”.','/wi/','wee','Oui, merci. — Yes, thank you.','Three letters, starting with o.','translation'),
q('fr-004',1,'Listen, then choose the phrase you hear.','Au revoir',['Bonjour','Merci','Bonsoir'],'Au revoir is a common way to say “goodbye”. The final r is pronounced in standard French.','/o ʁə.vwaʁ/','oh ruh-VWAHR','Au revoir, à bientôt ! — Goodbye, see you soon!','It is a farewell.','listening'),
q('fr-005',1,'Build: “Hello, thank you.”','Bonjour merci',[],'Bonjour starts the greeting, then merci expresses thanks. Punctuation can separate these two expressions.','/bɔ̃.ʒuʁ mɛʁ.si/','bohn-ZHOOR mehr-SEE','Bonjour, Paul. Merci ! — Hello, Paul. Thank you!','Say hello first, then thank you.','sentence_builder'),
q('fr-006',2,'Choose “My name is Léa.”','Je m’appelle Léa.',['Je suis merci.','Tu es Léa.','Bonjour Léa.'],'Je m’appelle means “my name is”, literally “I call myself”. It is a common introduction.','/ʒə ma.pɛl le.a/','zhuh mah-PELL lay-AH','Je m’appelle Paul. — My name is Paul.','Look for m’appelle.'),
q('fr-007',2,'Which phrase means “I am”?','Je suis',['Tu es','Il est','Je m’appelle'],'Je is “I” and suis is the je form of être, “to be”. Learn them together: je suis.','/ʒə sɥi/','zhuh swee','Je suis ici. — I am here.','The pronoun for “I” is je.'),
q('fr-008',2,'Type the French word for “you” when speaking to one friend.','Tu',[],'Tu is informal singular “you”. Use vous for politeness or when addressing more than one person.','/ty/','tü (rounded lips)','Tu es ici. — You are here.','Two letters. Unlike English, French distinguishes tu and vous.','translation'),
q('fr-009',2,'Listen, then choose what you hear.','Je suis ici.',['Je m’appelle Léa.','Tu es ici.','Bonjour, Paul.'],'Je suis ici means “I am here”. Ici describes where you are.','/ʒə sɥi i.si/','zhuh swee ee-SEE','Tu es ici. — You are here.','It starts with “I am”.','listening'),
q('fr-010',2,'Build: “My name is Paul.”','Je m’appelle Paul',[],'Keep je and m’appelle together before your name. This phrase is useful in both friendly and polite introductions.','/ʒə ma.pɛl pɔl/','zhuh mah-PELL pol','Je m’appelle Léa. — My name is Léa.','Start with “I”.','sentence_builder'),
q('fr-011',3,'Which phrase means “a coffee”?','Un café',['Une eau','Un thé','Le pain'],'Café is masculine, so “a coffee” is un café. The accent in café changes the final vowel sound.','/œ̃ ka.fe/','uhn kah-FAY','Un café, merci. — A coffee, thank you.','The word looks familiar in English.'),
q('fr-012',3,'How do you politely say “I would like”?','Je voudrais',['Je suis','Tu es','Au revoir'],'Je voudrais is a polite way to make a request, like “I would like” in English.','/ʒə vu.dʁɛ/','zhuh voo-DREH','Je voudrais un thé. — I would like a tea.','Look for voudrais.'),
q('fr-013',3,'Type the French word for “water”.','Eau',[],'Eau means “water”. The three letters eau make one vowel sound, similar to “oh”.','/o/','oh','De l’eau, s’il vous plaît. — Some water, please.','Three vowels, one sound.','translation'),
q('fr-014',3,'Listen, then choose the phrase you hear.','S’il vous plaît.',['Au revoir.','Merci beaucoup.','Je suis ici.'],'S’il vous plaît is the polite form of “please”. With a friend, you may use s’il te plaît.','/sil vu plɛ/','seel voo PLEH','Un café, s’il vous plaît. — A coffee, please.','A polite request often ends with this.','listening'),
q('fr-015',3,'Build: “I would like a coffee.”','Je voudrais un café',[],'A polite request follows je voudrais + the item. Use un with the masculine noun café.','/ʒə vu.dʁɛ œ̃ ka.fe/','zhuh voo-DREH uhn kah-FAY','Je voudrais un thé. — I would like a tea.','Begin with je voudrais.','sentence_builder'),
q('fr-016',4,'How do you ask “Where is the station?”','Où est la gare ?',['Je suis la gare.','La gare est ici.','Au revoir, madame.'],'Où means “where”. The accent distinguishes où (where) from ou (or). Gare is feminine: la gare.','/u ɛ la ɡaʁ/','oo eh lah gahr','Où est le café ? — Where is the café?','Start with the word for “where”.'),
q('fr-017',4,'Which phrase means “on the left”?','À gauche',['À droite','Tout droit','Ici'],'À gauche means “on the left” or “to the left”. À droite means “on the right” or “to the right”.','/a ɡoʃ/','ah gohsh','La gare est à gauche. — The station is on the left.','It is the opposite of à droite.'),
q('fr-018',4,'Type the French word for “here”.','Ici',[],'Ici means “here”. It names a place close to the speaker, just as “here” does in English.','/i.si/','ee-SEE','Le café est ici. — The café is here.','Three letters; it starts and ends with i.','translation'),
q('fr-019',4,'Listen, then choose the phrase you hear.','À droite',['À gauche','Bonjour','Tout droit'],'À droite means “to the right”. Tout droit, without the final e, means “straight ahead”.','/a dʁwat/','ah drwaht','Le café est à droite. — The café is on the right.','Listen for the final t sound.','listening'),
q('fr-020',4,'Build: “The station is here.”','La gare est ici',[],'The word order is the same as English here: subject (la gare), verb (est), then place (ici).','/la ɡaʁ ɛ i.si/','lah gahr eh ee-SEE','Le café est ici. — The café is here.','Start with “the station”.','sentence_builder'),
];
export const features=['French nouns have grammatical gender: learn un or une with each noun.','Tu and vous both mean “you”, but differ in politeness and number.','Nasal vowels use airflow through the nose; English respellings are only approximations.','The French r is usually formed at the back of the mouth.','Written endings are often silent; audio and spelling need to be learned together.','Accents matter: où means “where”, while ou means “or”.'];
