"use client";
import { useRef, useState } from 'react';
import { ArrowRight, Check, Volume2, Heart, Lightbulb, Trophy } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/learning/dialog';
import { Progress } from '@/components/ui/learning/progress';
import { RadioGroup, RadioGroupItem } from '@/components/ui/learning/radio-group';
import { features, Question } from '@/lib/learning/content';
import { Profile, isCorrect } from '@/lib/learning/model';
export function Choices({values,value,onChange}:{values:string[];value:string;onChange:(v:string)=>void}){return <RadioGroup value={value} onValueChange={onChange} className="choice-list">{values.map(v=><label key={v} className={`choice ${value===v?'chosen':''}`}><RadioGroupItem value={v}/><span>{v}</span></label>)}</RadioGroup>}
export function Onboarding({profile,learnerName,onClose,onSave}:{profile:Profile|null;learnerName:string;onClose:()=>void;onSave:(p:Profile)=>void}){
 const [step,setStep]=useState(0),[name,setName]=useState(profile?.name||learnerName),[level,setLevel]=useState(profile?.level||'Beginner'),[focus,setFocus]=useState(profile?.focus||'Everyday conversation'),[goal,setGoal]=useState(String(profile?.goal||10));
 const titles=['Bonjour! Let’s make this yours.','Where are you starting?','What brings you to French?','A little time, every day.','Your first chapter awaits.'];
 return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="flow-dialog"><div className="eyebrow">YOUR FRENCH JOURNEY · {step+1} OF 5</div><Progress value={(step+1)*20}/><DialogTitle className="flow-title">{titles[step]}</DialogTitle><DialogDescription>{['Learn French with English explanations. What should we call you?','This first course covers A1 foundations. Experienced learners can use it as a refresher.','We’ll keep your goal on your profile as your journey grows.','Choose a goal that fits your day. You can change it anytime.','A few things make French different from English. We’ll practise them one little step at a time.'][step]}</DialogDescription>
 {step===0&&<label className="input-label">Your name or nickname<input autoFocus maxLength={30} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Alex" autoComplete="nickname"/><small>Your preferences and progress are saved to your student account.</small></label>}
 {step===1&&<Choices values={['Beginner','Some French','Confident · here to review']} value={level} onChange={setLevel}/>}
 {step===2&&<Choices values={['Everyday conversation','Travel & new places','School & study','Just for the joy of it']} value={focus} onChange={setFocus}/>}
 {step===3&&<Choices values={['5 minutes','10 minutes','15 minutes','20 minutes']} value={`${goal} minutes`} onChange={v=>setGoal(v.split(' ')[0])}/>}
 {step===4&&<><ul className="feature-list">{features.map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><div className="inline-note">Your path: First words → About you → At the café → Out & about</div></>}
 <div className="flow-actions">{step>0&&<button className="plain-button" onClick={()=>setStep(step-1)}>Back</button>}<button className="primary" disabled={!name.trim()} onClick={()=>step<4?setStep(step+1):onSave({name:name.trim(),level,focus,goal:Number(goal),largeText:profile?.largeText||false})}>{step===4?'Start my journey':'Continue'}<ArrowRight size={18}/></button></div></DialogContent></Dialog>
}
export type Session={key:number;questions:Question[];mode:'lesson'|'daily'|'review'|'words'|'listening';unit:number};
export function Lesson({session,hearts,onClose,onAnswer,onComplete}:{session:Session;hearts:number;onClose:()=>void;onAnswer:(q:Question,correct:boolean,review:boolean)=>void;onComplete:(correct:number,total:number,seconds:number)=>void}){
 const [index,setIndex]=useState(0),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState<boolean|null>(null),[hint,setHint]=useState(false),[caption,setCaption]=useState(false),[audioError,setAudioError]=useState(''),[words,setWords]=useState<number[]>([]),[done,setDone]=useState(false),[retry,setRetry]=useState(false),[gentle,setGentle]=useState(session.mode==='review'),[scores,setScores]=useState<boolean[]>([]);
 const start=useRef(Date.now()),locked=useRef(false),completed=useRef(false);
 const question=session.questions[index]; const tokens=question.correctAnswer.split(' ');const ordered=tokens.map((text,i)=>({text,i})).reverse();
 const options=[question.correctAnswer,...question.incorrectAnswers].sort((a,b)=>{const hash=(s:string)=>[...s].reduce((n,c)=>n+c.charCodeAt(0),0)%19;return hash(a)-hash(b)});
 const paused=hearts===0&&!gentle&&feedback===null&&!done;
 function checkAnswer(){if(locked.current||!answer.trim())return;locked.current=true;const correct=isCorrect(answer,question.correctAnswer);setFeedback(correct);if(!retry){setScores([...scores,correct]);onAnswer(question,correct,gentle);} }
 function next(){if(index+1===session.questions.length){if(!completed.current){completed.current=true;onComplete(scores.filter(Boolean).length,scores.length,Math.max(1,Math.round((Date.now()-start.current)/1000)));}setDone(true);return;}setIndex(index+1);setAnswer('');setWords([]);setFeedback(null);setHint(false);setCaption(false);setAudioError('');setRetry(false);locked.current=false;}
 function speak(){if(!('speechSynthesis' in window)){setAudioError('Audio is unavailable in this browser. Use the transcript below.');setCaption(true);return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(question.audio);u.lang='fr-FR';u.rate=.78;const voice=window.speechSynthesis.getVoices().find(v=>v.lang.startsWith('fr'));if(voice)u.voice=voice;u.onerror=()=>{setAudioError('Audio could not play. Use the transcript below.');setCaption(true)};window.speechSynthesis.speak(u);}
 return <Dialog open onOpenChange={v=>{if(!v){if('speechSynthesis' in window)window.speechSynthesis.cancel();onClose()}}}><DialogContent className="flow-dialog lesson-dialog"><div className="lesson-dialog-top"><span className="eyebrow">{session.mode==='lesson'?`UNIT ${session.unit}`:session.mode.toUpperCase()} · {done?'COMPLETE':`${index+1} OF ${session.questions.length}`}</span><span className="heart-count"><Heart size={17}/>{hearts}</span></div><Progress value={done?100:index/session.questions.length*100}/>
 {done?<><Trophy className="completion-icon" size={60}/><DialogTitle className="flow-title">A little wiser. A little further.</DialogTitle><DialogDescription>You answered {scores.filter(Boolean).length} of {scores.length} correctly on the first try.</DialogDescription><div className="result-grid"><span><strong>{Math.round(scores.filter(Boolean).length/scores.length*100)}%</strong>accuracy</span><span><strong>{session.questions.reduce((sum,q,i)=>sum+(scores[i]?q.xpReward:0),0)}</strong>answer XP</span></div><p className="feedback-copy">{session.mode==='lesson'?(scores.filter(Boolean).length/scores.length>=.7?(session.unit===4?'You completed French Foundations! Keep your words fresh with daily practice.':'Chapter complete! Your next unit is ready.'):'You’re building the foundations. Try this chapter again to reach 70% and unlock the next one.'):'Practice complete. Your progress is being synced to your account.'}</p><button className="primary" onClick={onClose}>Back to my journey <ArrowRight size={18}/></button></>:paused?<><DialogTitle className="flow-title">Take a breath. You’re learning.</DialogTitle><DialogDescription>Your hearts need a little rest. Keep practising gently; correct answers will restore hearts.</DialogDescription><button className="primary" onClick={()=>setGentle(true)}>Continue with gentle practice <Heart size={18}/></button></>:<><DialogTitle className="flow-title">{question.prompt}</DialogTitle><DialogDescription>{question.type==='sentence_builder'?'Tap the words in the right order. Tap an answer word to put it back.':question.type==='translation'?'Write your answer in French. Accents matter; capital letters don’t.':question.type==='listening'?'Play the audio, or use the transcript if you prefer.':'Choose the answer that fits.'}</DialogDescription>
 {question.type==='listening'&&<div className="audio-section"><button className="audio-button" onClick={speak}><Volume2 size={24}/> Play French audio</button><button className="text-button" onClick={()=>setCaption(!caption)}>{caption?'Hide':'Show'} transcript</button>{caption&&<p lang="fr">{question.audio}</p>}{audioError&&<p role="status">{audioError}</p>}</div>}
 {question.type==='translation'?<form onSubmit={e=>{e.preventDefault();checkAnswer()}}><input className="answer-input" aria-label="Your French answer" autoFocus autoComplete="off" value={answer} disabled={feedback!==null} onChange={e=>setAnswer(e.target.value)}/></form>:question.type==='sentence_builder'?<div><div className="sentence-answer" aria-label="Your sentence">{words.length===0?<span>Your sentence goes here…</span>:words.map((id,i)=><button key={id} disabled={feedback!==null} onClick={()=>{const next=words.filter((_,k)=>k!==i);setWords(next);setAnswer(next.map(n=>tokens[n]).join(' '))}}>{tokens[id]}</button>)}</div><div className="word-bank">{ordered.map(({text,i})=><button key={i} disabled={words.includes(i)||feedback!==null} onClick={()=>{const next=[...words,i];setWords(next);setAnswer(next.map(n=>tokens[n]).join(' '))}}>{text}</button>)}</div></div>:<RadioGroup className="answer-options" value={answer} onValueChange={setAnswer} disabled={feedback!==null}>{options.map((o,i)=><label key={o} className={`answer-option ${answer===o?'chosen':''} ${feedback!==null&&o===question.correctAnswer?'correct-option':''}`}><RadioGroupItem value={o}/><span lang="fr">{o}</span><small>{i+1}</small></label>)}</RadioGroup>}
 {audioError&&question.type!=='listening'&&<p className="inline-note" role="status">{audioError}</p>}{feedback===null?<><button className="text-button hint-button" onClick={()=>setHint(!hint)}><Lightbulb size={16}/>{hint?'Hide hint':'A little hint'}</button>{hint&&<p className="inline-note">{question.hint}</p>}<button className="primary" disabled={!answer.trim()} onClick={checkAnswer}>Check answer <Check size={18}/></button></>:<div className={`feedback ${feedback?'success':'try-again'}`} role="status"><strong>{feedback?'Très bien! You found the right expression.':'You gave it a try. Let’s build on that.'}</strong><p> {feedback?'Answer':'Better'}: <b lang="fr">{question.correctAnswer}</b></p><p>{question.explanation.en}</p><p className="pronunciation"><span lang="fr">{question.pronunciationGuide}</span> · {question.respelling} <button aria-label="Hear the correct answer" onClick={speak}><Volume2 size={16}/></button></p><p><b>Another example:</b> {question.example}</p>{!feedback&&<small>Saved to Your Mistakes for spaced review.</small>}<div className="flow-actions">{!feedback&&<button className="plain-button" onClick={()=>{setRetry(true);setAnswer('');setWords([]);setFeedback(null);locked.current=false}}>Try again</button>}<button className="primary" onClick={next}>{index+1===session.questions.length?'Finish practice':'Continue'}<ArrowRight size={17}/></button></div></div>}
 </>}
 </DialogContent></Dialog>
}
